### ISSUE TITLE
Backup not Working

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#10]
@rajesh-rajagopal 
Now you Check it .Copy file from ubunto  to Storage server

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
Its not fixed.. I got same error..
![image](https://user-images.githubusercontent.com/18652643/50829556-defb8f00-136a-11e9-890f-33b94f94d664.png)

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Some Clarification Pls Call Elango Sir

**Comment by indykish** [comment]
Duplicate of #11
