### ISSUE TITLE
Backup Problem 

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#11]
@rajesh-rajagopal 
I spoke to the support guy from Stackup Storage Team they Said that is Ubuntu permission problem so please check it and let us know. If you want to speak them, we will share their number

**Comment by Servernet1** [comment]
u only mounted the storage server

**Comment by rajesh-rajagopal** [comment]
For the first time i mount storage server using nfs unix, but at the time storage server is not mount in windows.. so you can't backup images from your windows server to storage server. 

So you was called stackbox team they try to mount with samba in unix(176) server. and they only mount the storage to megamswasa(176) server.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Ok
