### ISSUE TITLE
Issue No:8 We are not able to create Vm

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#12]
@rajesh-rajagopal 

Please check ur E-mail 
I send the Details

**Comment by rajesh-rajagopal** [comment]
@Servernet1  

You are requested 1TB of HDD for VMs. 

But there is only 415 GiB of storage is available in ceph.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
  shall u Enable 1 More 2Tb  Because 2 2Tb  Desabled

**Comment by rajesh-rajagopal** [comment]
Ok. Add 2tb HDD in ceph storage

**Comment by Servernet1** [comment]
@rajesh-rajagopal 

k please create and mount the VM in 177 server 
thats details wise Mounting Then let me know

**Comment by vijaykanthm28** [comment]
2 HDD added on ceph storage by @rajesh-rajagopal 
@vijaykanthm28  working on VM create issue

**Comment by vijaykanthm28** [comment]
@Servernet1  VM create issue fixed
@rajesh-rajagopal is now working on VM disk partitions as you requested.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Today Demo to Custamer that's VM so Pls

**Comment by vijaykanthm28** [comment]
@Servernet1  disk partitioned as you requested.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
ji restart pannalum mounting partition change gathu la

**Comment by vijaykanthm28** [comment]
@Servernet1 Its mounting point added in ftab, so it dosn't change even restart.

**Comment by Servernet1** [comment]
@vijaykanthm28 
kk
