### ISSUE TITLE
Issue No:9 ISO disk mount into VM  

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#13]
@rajesh-rajagopal 
![screenshot 8](https://user-images.githubusercontent.com/46295662/51982337-ba9f5800-24bb-11e9-832f-f9adc2bc3099.png)

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
I can't understand your issue...

What is actually you did..?

**Comment by Servernet1** [comment]
We want to install XRDP . So we need to mount Suse Linux OS image as a drive in the mentioned path. You did the same for the last server.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
![screenshot  @11](https://user-images.githubusercontent.com/46295662/51983013-a8261e00-24bd-11e9-9b49-e3a5d1e2bba3.png)

**Comment by rajesh-rajagopal** [comment]
Ok.

We will mount suse iso into VM

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
once u  finish mount pls let me know

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
appied Suse Os in storage

**Comment by rajesh-rajagopal** [comment]
Ok. Thank you..

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Again same problem face it  so pls check it
![51983013-a8261e00-24bd-11e9-9b49-e3a5d1e2bba3](https://user-images.githubusercontent.com/46295662/52029744-9898ea80-253a-11e9-869f-b16104267053.png)

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
I just mount suse iso as a disk into VM..
last time also i did the same.
From your side only install xrdp.. I'm not install anything in suse VM.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
kk

**Comment by Servernet1** [comment]
Please check once again on the new server, Which is installed on yesterday.  We are finding difficult to identify.

**Comment by rajesh-rajagopal** [comment]
what i need to check..?

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
How to find Iso image in Vdc disk

**Comment by Servernet1** [comment]
we tried to find iso image path via this below command. But not able to find
mount | grep /media/iso
or
mount | awk '/\/media\/iso/ {print $0 }'

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Pls change the host name 
Host name Should be Hana-Indus

**Comment by rajesh-rajagopal** [comment]
These are already conveyed to you chandran...
Refer these [docs](https://docs.google.com/document/d/1u_UKd_gPhd5Ag-9GMgdyXZaDY4gXM7-giKipACEPQMk/edit)

**Comment by rajesh-rajagopal** [comment]
This issue has been fixed. so i close this issue.
