### ISSUE TITLE
Issue no:13 Suse Os Mounted

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#15]
@rajesh-rajagopal 
I coppied Suse Ios sp3 in suse linux Folder in Storage So  Check it
once u finished then let me know

**Comment by rajesh-rajagopal** [comment]
No need to build new images. 
I already resized existing VM root(/) size to 64 GB. so you will upgrade suse 12 SP2 into SP3 in browser manually.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
Yesterday Upgrade Sp2 To Sp3 But Thats Process was Not Complete  
Thats why We Coppied Suse Sp3  in Storage So pls Use the Suse Sp3 Ios

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
pls Mount to Suse sp3 DVD2 in that's Server

**Comment by vijaykanthm28** [comment]
virsh attach-disk <vm-name> <iso-file-path> 
Ex. 
virsh attach-disk nodelet-15763-hana-agdh.rioos.com /mnt/servnew/iso/SL-suse-SP3.iso 


Run the above comment on 177server 

To mount the disk run the below command on VM 


mkdir /media/iso
sudo mount /dev/vdc2/ /media/iso

**Comment by Servernet1** [comment]
![screenshot 12](https://user-images.githubusercontent.com/46295662/52161726-ac398200-26ef-11e9-8046-5a96f8fc014d.png)
@vijaykanthm28

**Comment by vijaykanthm28** [comment]
virsh attach-disk nodelet-15763-hana-agdh.rioos.com /mnt/servnew/iso/SL-suse-SP3.iso --target vdc

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
suse linux disk is mounted in VM /media/sp3-sio

**Comment by rajesh-rajagopal** [comment]
Now, i close this issue.
