### ISSUE TITLE
Issue no :14Mounted Suse os

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#16]
U  finished mounted in suse ios sp3 in new server pls let me know
 @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
Please read every comment in all issue.
Suse ISO Disk is mounted in hanaindus VM, Already I informed in previous issue.

**Comment by rajesh-rajagopal** [comment]
Verify with Virtual Machine..

**Comment by Servernet1** [comment]
kk 
i already ask u how to mountting and partition in suse  
@rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

last week @vijaykanthm28 sent a mail with screenshot to mount and partition disk into suse. Did you saw that..?

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
thats file was not open bcs some demage error showing so pls reset the doc

**Comment by rajesh-rajagopal** [comment]
ok. I will resend as zip file. once you received the zip file you will extract and check it.

finally close this issue.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
 thank u
