### ISSUE TITLE
Issue :Change the Hard disk size in current Vm 

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#18]
@rajesh-rajagopal                                                                                                                                                                 yesterday i create one VM name Rapro in Centos and Hd size 303 gb but Customer says only 4 gb show the 
Disk size so pls check and  solve it then let me know

**Comment by Servernet1** [comment]
yesterday i create one VM name Rapro in Centos and Hd size 303 gb but Customer says only 4 gb show the 
Disk size so pls check and  solve it then let me know @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
Ok. I will check it

**Comment by rajesh-rajagopal** [comment]
VM root size is changed..
