### ISSUE TITLE
issue :VM is slow process

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#19]
@rajesh-rajagopal 
Ip 91,152 thats Two VM process is very slow Can u analyse

**Comment by rajesh-rajagopal** [comment]
Ok. I will check it ..

**Comment by Servernet1** [comment]
the two VM process is  two deffend

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
the two VM running is two different server but the process is very slow. that slow problem is the third time accord. some time process is normal some time  slow process so pls analyze and let me know

**Comment by rajesh-rajagopal** [comment]
Yes..

Both VMs are running in separate server, also server have enough memory.

Checking, If i found any issues let you know..

**Comment by Servernet1** [comment]
ok thank u

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

Did you changed anything in VM..?

What you did in VM before process slow..?

Because so far, its working fine. and I'm checking for the solution..

**Comment by Servernet1** [comment]
no changing 
@rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
If user change or install any software..?

**Comment by Servernet1** [comment]
no y any problem u identify
 @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
Full memory size is used in Megamboomi(175) server.
You can see memory using using `free -m` command
![image](https://user-images.githubusercontent.com/18652643/52695489-b468ab80-2f92-11e9-9b22-306da6154abe.png)

In Megamboomi(175) server have 128 GB of memory.

3 instances are running on 175 server.
Memory size assigned on VMs
```
hana - 96
urs - 6
server4 - 28
```
Total assigned size is 130, actual memory is only 128 GB. System OS also need some memory to run.

**Comment by rajesh-rajagopal** [comment]
Now, I clear some cached memory

![image](https://user-images.githubusercontent.com/18652643/52695559-e5e17700-2f92-11e9-8354-dd195d375f59.png)

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
Can i close this issue.

**Comment by indykish** [comment]
@rajesh-rajagopal  Thanks for solving this. Can you add a post in Wiki, saying `How to debug VM when its slow`

and another cheat sheet with `Common Unix commands`, this must be there some where in our old https://github.com/megamsys.
