### ISSUE TITLE
Issue:Vm Backup

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#21]
how to VM backup rbd to local

**Comment by vijaykanthm28** [comment]
*create your directory to backup*

```
mkdir /mnt/servnew/hana-backup/
```

Backup rbd block storge to raw disk file 
```
rbd export rio-hana.servernet.in-disk-0 /mnt/servnew/hana-backup/rio-hana.servernet.in-disk-0.img --pool=rio
```

replace  `rio-hana.servernet.in-disk-0` with actual name of rbd image which is you want to backup 

list vm storages 

```
rbd ls rio
```

**Comment by rajesh-rajagopal** [comment]
Disk is not mounted in server.

You can check using `lsblk` command
![image](https://user-images.githubusercontent.com/18652643/52780334-f4ea2700-306f-11e9-9a27-99bc729efc09.png)

Once the disk is mounted, you can backup ceph image into disk using below instructions.

```
$ sudo mkdir /home/rioos/hdd
$ sudo mount /dev/<disk_id> /home/rajesh/hdd
$ sudo mkdir /home/rioos/hdd/hana-backup

backup ceph images
$ sudo rbd export rio-nemha-hanaindus-44151.servernet.in-disk-1 /home/rioos/hdd/hana-backup/rio-hanaindus-disk-backup.img --pool=rio

$ sudo rbd export rio-o5x7s-hanaindus-74331.servernet.in-disk-0 /home/rioos/hdd/hana-backup/rio-hanaindus-root-backup.img --pool=rio
```

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
only u send export cmd

**Comment by rajesh-rajagopal** [comment]
@Servernet

Run below command to remove image from ceph storage

rbd rm rio/rio-nemha-hanaindus-44151.servernet.in-disk-1

rbd rm rio/rio-o5x7s-hanaindus-74331.servernet.in-disk-0

**Comment by rajesh-rajagopal** [comment]
Once VM is removed from ceph storage run this command to remove disk from ceph storage

rbd ceph out 0
rbd ceph out 1

**Comment by rajesh-rajagopal** [comment]
@Servernet1  Did you remove disk from ceph storage.?

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

I will remove backup image from ceph storage..

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
2 TB HDD remove from ceph storage..

**Comment by rajesh-rajagopal** [comment]
VM is backup into External HDD so this issue is close..
