### ISSUE TITLE
Issue: klastaring problem

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#22]
@rajesh-rajagopal 
we should not use 500 rpm hard disk for klastaring

**Comment by Servernet1** [comment]
we added the 1 hard disk in 2 TP in 177 server so pls check and remove 2 2TP in 176 server

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
we added the new one 2 TB hard disk in 177 server.
We put the Hard disk in no 2 place the 4th node.
so pls add the new disk and remove other two 2TB hard disks.
once u add the new hard disk then backup the VM name nodelet-11716-o5x7s-hanaindus-74331.servernet.in 
and start the VM using the new hard disk. once u finished let me know

**Comment by rajesh-rajagopal** [comment]
I checked right now in 177 server. there is no extra active disk.

Please refer this issue https://github.com/rioadvancement/rioos/issues/21

Check disk is up then you can do backup image into disk.

**Comment by Servernet1** [comment]
177 might have the board issue. So that We are using usb boot. Please remove the 2 nos 2 TB hdds(5400 )RPM from 176 and add the New 7200 K RPM 2 TB HDD,

**Comment by rajesh-rajagopal** [comment]
In which server you was add new 2 TB HDD..

**Comment by Servernet1** [comment]
Now we have added in 177 but which is not working. So first we have to take a backup from 176 to storage server then remove from 176 . Finally we have to add @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
But storage server is not working.. I can't copy file from 176 server to storage server

**Comment by Servernet1** [comment]
Is it possible to copy to External HDD

**Comment by rajesh-rajagopal** [comment]
Yes its possible.. 

External HDD have enough size.

**Comment by Servernet1** [comment]
Ok. Please call me for a clarification.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
finished export file to external hard disk 
here I using the cmd and check it
sudo rbd export rio-o5x7s-hanaindus-74331.servernet.in-disk-0                                                                                         /home/rioos/exthdd/rio-hanaindus-root-backup.img --pool=rio
once u finished let me know

**Comment by rajesh-rajagopal** [comment]
Please backup both images.

**Comment by Servernet1** [comment]
We need only one image only @rajesh-rajagopal

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
only u send export cmd only. 
No other cmd
same export cmd using two different VM. 
pls send another cmd

**Comment by rajesh-rajagopal** [comment]
Both export command only for HanaIndus VM..

**Comment by Servernet1** [comment]
We copied the file via below command.
sudo rbd export rio-o5x7s-hanaindus-74331.servernet.in-disk-0 /home/rioos/exthdd/rio-hanaindus-root-backup.img --pool=rio

and finished. We have a confusion now. Can you call me for a clarification.

**Comment by rajesh-rajagopal** [comment]
You must run both these command..

$ sudo rbd export rio-nemha-hanaindus-44151.servernet.in-disk-1 /home/rioos/hdd/hana-backup/rio-hanaindus-disk-backup.img --pool=rio

$ sudo rbd export rio-o5x7s-hanaindus-74331.servernet.in-disk-0 /home/rioos/hdd/hana-backup/rio-hanaindus-root-backup.img --pool=rio

**Comment by rajesh-rajagopal** [comment]
Hanaindus VM run with 2 disks. one for OS another disk used for partition process (like /hana/data /hana/log) 

So you must backup both disks.

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
another cmd also finished the progress pls check it and let me know
I run the 2 cmd that's finished

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
finished another cmd so check it

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

New HDD can added to ceph storage..

**Comment by rajesh-rajagopal** [comment]
This issue has been closed.

Bcz, windows VM slow on 5300 rpm HDD, Now its changed into ceph
