### ISSUE TITLE
Issue:Add the new Hard disk

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#25]
@rajesh-rajagopal 
Add the new hard disk in 177 server.and hanaindus backup move to the new hard disk and start the VM using this new hard disk. then let me know

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

Please open your email, read all the mail.

Bcz, I already informed `New 2TB HDD is added to ceph storage`
Also I create a new issue for `Backup restore of hanaindus image`.. So kindly open your email and read all the mail received from rioos issue. This is an duplicate issue. Kindly delete this.

**Comment by rajesh-rajagopal** [comment]
Duplicate of https://github.com/rioadvancement/rioos/issues/24. Close this isse
