### ISSUE TITLE
Issue:Hardware Configuration for Suse Linux

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#27]
@rajesh-rajagopal 
Is it possible to disable Hardware configuration as below in. If Yes, Please disable for HANAINDUS server only.
 "Allow migration to a virtual machine host with a different processor version."
 Please call me if you need any clarification.

**Comment by rajesh-rajagopal** [comment]
@Servernet1 

hanasap VM  also running in SUSE linux. 
There is no one changed manually on that VM, then why is it necessary to change in hanaindus..?

**Comment by Servernet1** [comment]
HanaSAP is difference between Hanaindus.

HANASAP - Linux and Windows based - Normal - B1 SAP

HANAINDUS -  Pure Linux Based -  Pure   HANA SAP
@ @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
Ok.

Is SAP is not running on HANAINDUS VM with current configuration..?

**Comment by Servernet1** [comment]
Please call Ilango sir @rajesh-rajagopal

**Comment by Servernet1** [comment]
We are getting the below error.

If it is of X86_64 CPU and put on virtual environment, then please apply this workaroung.
 

Symptom
Failed to update HANA 2.0 due to "CPU is not supported. Instruction set 'sse4.2' is missing" error

INFO: | Upgrade failed 
INFO: | Checking system requirements failed 
INFO: | CPU is not supported. Instruction set 'sse4.2' is missing.

Environment
 HANA 2.0
Cause
From HANA 2.0 SPS03 started checking the necessary cpu type "sse4.2" when installing or updating HANA.

Resolution
If you are using virtual machine such as VMWare, please check if you can select the newer cpu type for enabled SSE4.2 on the Virtual Environment processor configuration with VM admin.

    For example, if using Hyper-V and you have configured "Set-VMProcessor -CompatibilityForMigrationEnabled $true", SSE4.2 wouldn't be visible and therefore the HANA installation of SPS3 would fail.
    1) It might be caused by vCenter EVC mode limited all of VMs to using old CPU type in default.
    2) In the Hardware Configuration, Check if disabling "Allow migration to a virtual machine host with a different processor version." can change enables sse4.2.

 @rajesh-rajagopal

**Comment by Servernet1** [comment]
please call us.
@rajesh-rajagopal

**Comment by Servernet1** [comment]
how to open virt-manager in YAST
any cmd? @rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
There is no Virt Manager, Libvirt will manage automatically

**Comment by Servernet1** [comment]
How can we see the Processor settings in  Libvirt
@rajesh-rajagopal

**Comment by Servernet1** [comment]
Please come on anydesk to see our system for a minute to resolve the issue.
@rajesh-rajagopal

**Comment by rajesh-rajagopal** [comment]
No UI for processor settings. You can select from our rioos launch page it will automatically create xml file.

launch VM used with xml properties

**Comment by vijaykanthm28** [comment]
@Servernet1  Can i Restart the server `hana-indus` ? for the cpu compatibility changes.

**Comment by vijaykanthm28** [comment]
@Servernet1  you have changed cpu `<cpu mode='host-passthrough'/>` mostly that will solve your problem, and that is what i tried to change.

**Comment by vijaykanthm28** [comment]
@Servernet1  let us know once your problem solved.

**Comment by Servernet1** [comment]
<cpu mode='host-passthrough'/>
<qemu:arg value='-cpu'/>
    <qemu:arg value='host,migratable=off,+invtsc'/>
pls verify the above commands format are right.
@vijaykanthm28

**Comment by vijaykanthm28** [comment]
>  pls verify the above commands format are right. @vijaykanthm28

I don't see any commands in this conversation. Please refer what command

**Comment by Servernet1** [comment]
@vijaykanthm28 
<cpu mode='host-passthrough'/>
<qemu:arg value='-cpu'/>
    <qemu:arg value='host,migratable=off,+invtsc'/>
pls verify the above commands format are right.

**Comment by Servernet1** [comment]
@vijaykanthm28 
<cpu mode='host-passthrough'/>
<qemu:arg value='-cpu'/>
    <qemu:arg value='host,migratable=off,+invtsc'/>
pls verify the above commands format are right.

**Comment by Servernet1** [comment]
<cpu mode='host-passthrough'/>

pls verify the above commands format are right.
@vijaykanthm28

**Comment by vijaykanthm28** [comment]
> pls verify the above commands format are right.
> @vijaykanthm28
You cannot use the above parameters in XML we use KVM emulator that doesn't support the above flag.

**Comment by vijaykanthm28** [comment]
I close this issue because `<cpu mode='host-passthrough'/>` should solve your issue. 
this is what doing the process of https://www.altaro.com/hyper-v/configure-cpu-compatibility-mode-hyper-v/
