### ISSUE TITLE
Issue:Putty was not connected

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#29]
Server 177

**Comment by vijaykanthm28** [comment]
@Servernet1 update the screen short for (`free -m` , `df -h` and `top` )

**Comment by Servernet1** [comment]
@vijaykanthm28 
![IMG-20190403-WA0002](https://user-images.githubusercontent.com/46295662/55454616-24dc9200-55fe-11e9-8e2c-7021997aebfb.jpg)

**Comment by vijaykanthm28** [comment]
@Servernet1 in that server,  is OS booting via Internal HDD or external HDD ?
Can you run command `df -h` and `lsblk` commands ?

**Comment by Servernet1** [comment]
@vijaykanthm28 
same error not working

**Comment by vijaykanthm28** [comment]
in that server, is OS booting via Internal HDD or external HDD ?

**Comment by Servernet1** [comment]
@vijaykanthm28 
external

**Comment by Servernet1** [comment]
@vijaykanthm28 
175 server also now not connecting via putty
so kindly check it and let me know

**Comment by vijaykanthm28** [comment]
Did you restart that server (175)?

**Comment by Servernet1** [comment]
@vijaykanthm28 
no

**Comment by vijaykanthm28** [comment]
the network is changed to private gateway thats why you can't ssh through your public ip 
It will change gateway only If you restart server or restart the network. 
that's why i asked you.

**Comment by Servernet1** [comment]
@vijaykanthm28 
command please to run

**Comment by Servernet1** [comment]
@vijaykanthm28 
if we put any cmd on that server kindly let me know

**Comment by vijaykanthm28** [comment]
- First you have delete private default gateway using below command 
`ip route del default`

- Then add your public gateway 
`ip route add default dev riopub via <public-gateway-ip> onlink`

replace `<public-gateway-ip>` with your actual public gateway IP

**Comment by Servernet1** [comment]
we run this cmd 177 and 175 servers right?
 
@vijaykanthm28

**Comment by Servernet1** [comment]
we run this cmd 177 and 175 servers right?
 
@vijaykanthm28

**Comment by vijaykanthm28** [comment]
No. 
I have run that command on 175 server. 
In server 175 has network issue. but in server 177 External disk has issue.
