### ISSUE TITLE
issue:Mount the HDD 

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#31]
@indykish 
I connect the External Hdd so kindly Mount the Hdd in 175 server

**Comment by Servernet1** [comment]
ji kindly send the rbd usage cmd

**Comment by rajesh-rajagopal** [comment]
what command do you need..?

**Comment by Servernet1** [comment]
ji if i  launch any vm only launch the 175 server
how much convert the vm size that cmd

**Comment by rajesh-rajagopal** [comment]
`rbd ls rio` it will list your VM

**Comment by Servernet1** [comment]
ji i know this cmd but i want how much convert the current vm size vhdx to raw file that cmd i need

**Comment by rajesh-rajagopal** [comment]
Use this command to convert vhdx image to raw image
`qemu-img convert -f vhdx -O raw sigma2.vhdx  rbd:rio/sigma2.img`
