### ISSUE TITLE
issue:How to find out img file size

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#32]
ji I need know  img file size cmd
server 175
rbd ls rio
hana_server.img. I need know this img file size
there is any cmd ?
![IMG_20190405_122357 1](https://user-images.githubusercontent.com/46295662/55610327-4c6b6000-57a0-11e9-9905-1efe889fc214.jpg)

 kindly send the cmd
@indykish

**Comment by rajesh-rajagopal** [comment]
use disk-usage command to find out image size 
rbd disk-usage rio/hana_server.img

**Comment by Servernet1** [comment]
thank u
