### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#33]
ji server 175
i need know this img file hana_server.img source of the this Vm name: nodelet-11301-jfz5y-hana-04571.servernet.in
![IMG_20190405_131955](https://user-images.githubusercontent.com/46295662/55612397-d1a54380-57a5-11e9-92d0-a48c97eb3288.jpg @indykish 
![IMG_20190405_131955](https://user-images.githubusercontent.com/46295662/55612776-a66f2400-57a6-11e9-9f2a-203983140d9c.jpg)

**Comment by rajesh-rajagopal** [comment]
@Servernet1 
You ll also see the VM details..

Simply use `virsh edit <VM_Name> like this. 

For ex: virsh edit nodelet-11301-jfz5y-hana-04571.servernet.in
It will open xml file, there you will find out VM disk details.

This VM contains 2 Disks.
* rio-1128858528191938560-disk-0
* hana_server.img

![image](https://user-images.githubusercontent.com/18652643/55613628-cf90b400-57a8-11e9-84f4-b52b4cb7631e.png)

**Comment by Servernet1** [comment]
thank u
