### ISSUE TITLE
Issue:Vm is failed

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#34]
ji i launch one vm name : imayam but that vm is failed so kindly check and if i launch any vm only launch in 175 server based vm so kindly cheak and let me know
@indykish

**Comment by Servernet1** [comment]
just now lunch another vm
core:6
ram:4
hdd:400
thats also failed so kindly check and let me know
also assained private ip but not assaigned state so cheak it 
@indykish

**Comment by Servernet1** [comment]
@indykish 
any updates for that problem

**Comment by Servernet1** [comment]
ji any updates 
@indykish

**Comment by Servernet1** [comment]
@indykish 
ji any updates

**Comment by vijaykanthm28** [comment]
Working on your issue, update you soon

**Comment by Servernet1** [comment]
VM 1
Name :New server1
Os :Windows 2012R2
Cpu :8
Ram :16
HD :400
Ip :private

VM 2
Name : New server2
Os :ubuntu
Cpu :8
Ram :16
HD :250
Ip :public

kindly create this 2 vm launch in 175 server
@vijaykanthm28

**Comment by vijaykanthm28** [comment]
Both VM launched 

![Screenshot from 2019-04-30 15-23-51](https://user-images.githubusercontent.com/13815978/56954275-09f93100-6b5c-11e9-9a6e-a5c2a83612b4.png)

**Comment by vijaykanthm28** [comment]
Both VM launched

**Comment by Servernet1** [comment]
ubuntu vm working 
but windows vm not working 
kindly check it
 if i open console in the windows vm black screen appered
@vijaykanthm28

**Comment by Servernet1** [comment]
![tt](https://user-images.githubusercontent.com/46295662/56955230-6d845e00-6b5e-11e9-8e86-1a490c026a46.png)
@

**Comment by vijaykanthm28** [comment]
![Screenshot from 2019-04-30 16-50-08](https://user-images.githubusercontent.com/13815978/56958488-0b305b00-6b68-11e9-832b-66efafaf74f7.png)


check ur network connection is shows to me

**Comment by Servernet1** [comment]
kkk thank u ji @vijaykanthm28
