### ISSUE TITLE
Issue No.4

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#5]
We want to restart the Rioos api server for the login screen.

It shows there was no space in the device. So we want to delete the unwanted images. So if you could call us we can explain and send us the file.

**Comment by Servernet1** [comment]
we need a imaged stored path and delete command to delete the unwanted images.
Because we have to verify and delete the unwanted images. Please let us know. Now we are not able to login to rioos

**Comment by rajesh-rajagopal** [comment]
103.212.204.176 server have only 72G of / size.

* RioOS used storage of 38G.
* You are copied IMAYAM-new.vhdx image into /var/lib/rioos/servernet repository.
* IMAYAM-new.vhdx storage size is 36G. so it occupy 100% of storage size.

If you are used, then delete unwanted images. 

Now i manually delete IMAYAM-new.vhdx image. using remove command 
`rm /var/lib/rioos/servernet/IMAYAM-new.vhdx`

**Comment by rajesh-rajagopal** [comment]
> we need a imaged stored path and delete command to delete the unwanted images.
> Because we have to verify and delete the unwanted images. Please let us know. Now we are not able to login to rioos

Launched vm  stored in ceph storage. You can see using `rbd ls rio` . It not used / storage size. VM launched only in ceph storage. ceph is using 3 disk in 103.212.204.175 server.
