### ISSUE TITLE
Storage Files - Not able to access

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#6]
Issue No 5. We are not able to access the storage files
  rioos@megamswasa:/mnt/servnew

**Comment by rajesh-rajagopal** [comment]
I umount storage form 103.212.204.176 server. Bcz it not mount functionally. 

I can't copy file from 103.212.204.176 machine to /mnt/servnew

I ask storage server credentials.

**Comment by rajesh-rajagopal** [comment]
refer issue https://github.com/rioadvancement/rioos/issues/2

**Comment by Servernet1** [comment]
user name : Backup
password : 1234
