### ISSUE TITLE
Server4 VM not working

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#7]
@rajesh-rajagopal 
Not working 
This Vm
rioos@megambomi server:(nodelet-10998-uy2u1-server4-30631.servernet.in)

**Comment by rajesh-rajagopal** [comment]
Fix:-

Ceph storage is full.

**Comment by rajesh-rajagopal** [comment]
![image](https://user-images.githubusercontent.com/18652643/50631245-ad00bc00-0f69-11e9-818d-4608701a4b1a.png)
Now i removed unwanted storage

**Comment by Servernet1** [comment]
@rajesh-rajagopal 
working and how to delete unwanted img file and vm id in ceph cmd
