### ISSUE TITLE
Change the time in existing VMs

### ISSUE THREAD

**Issue by Servernet1** [rioadvancement/rioos#9]
@rajesh-rajagopal 
How to Change the time in Running Vm

**Comment by rajesh-rajagopal** [comment]
@Servernet1 New VM have automatically set server timezone.

If you want to change existing VMs timezone, you can do it manually in virsh xml files.

List VMs using 
$ virsh list --all
$ virsh edit <VM_NAME>

Change clock `utc` to `localtime`
_sample_

<clock offset='utc'/>

<clock offset='localtime'/>

and save file.

Once restart VM time will be changed.
